pipelines:
    - name: demo_gosvc
      steps:
        - name: step1
          type: Bash
          configuration:
            inputResources:
              - name: MyPropBag
          execution:
            onExecute:
              - echo "Hi"